version: "3.9"
services:
  rest_api:
    networks:
      - rest-api-network
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "8081:8081"
    depends_on:
      - redis
      - mysql
      - phpmyadmin
  redis:
    networks:
      - rest-api-network
    image: "redis:7.0.4-alpine3.16"
    ports:
      - "6379:6379"
  mysql:
    image: "mysql:8.0.30"
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - rest-api-network
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3306:3306"
  phpmyadmin:
    image: 'phpmyadmin:latest'
    depends_on:
      - mysql
    restart: always
    networks:
      - rest-api-network
    ports:
      - "8080:80"
    env_file:
      - .env

networks:
  rest-api-network:



